name: protoframe
description: Binary frame protocol encoder/decoder.
version: 0.2.1
repository: https://github.com/Kitjesen/brainstem

environment:
  sdk: ^3.10.0

resolution: workspace

dependencies:

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
