// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

/// <summary>
/// Initializes a PCAN Channel
/// </summary>
/// <param name="Channel">"The handle of a PCAN Channel"</param>
/// <param name="Btr0Btr1">"The speed for the communication (BTR0BTR1 code)"</param>
/// <param name="HwType">"Non-PnP: The type of hardware and operation mode"</param>
/// <param name="IOPort">"Non-PnP: The I/O address for the parallel port"</param>
/// <param name="Interrupt">"Non-PnP: Interrupt number of the parallel port"</param>
/// <returns>"A TPCANStatus error code"</returns>
@ffi.Native<
  ffi.Uint32 Function(ffi.Uint16, ffi.Uint16, ffi.Uint8, ffi.Uint32, ffi.Uint16)
>()
external int CAN_Initialize(
  int Channel,
  int Btr0Btr1,
  int HwType,
  int IOPort,
  int Interrupt,
);

/// <example>f_clock=80000000,nom_brp=10,nom_tseg1=5,nom_tseg2=2,nom_sjw=1,data_brp=4,data_tseg1=7,data_tseg2=2,data_sjw=1</example>
/// <returns>"A TPCANStatus error code"</returns>
@ffi.Native<ffi.Uint32 Function(ffi.Uint16, ffi.Pointer<ffi.Char>)>()
external int CAN_InitializeFD(int Channel, ffi.Pointer<ffi.Char> BitrateFD);

/// <summary>
/// Uninitializes one or all PCAN Channels initialized by CAN_Initialize
/// </summary>
/// <remarks>Giving the TPCANHandle value "PCAN_NONEBUS",
/// uninitialize all initialized channels</remarks>
/// <param name="Channel">"The handle of a PCAN Channel"</param>
/// <returns>"A TPCANStatus error code"</returns>
@ffi.Native<ffi.Uint32 Function(ffi.Uint16)>()
external int CAN_Uninitialize(int Channel);

/// <summary>
/// Resets the receive and transmit queues of the PCAN Channel
/// </summary>
/// <remarks>
/// A reset of the CAN controller is not performed.
/// </remarks>
/// <param name="Channel">"The handle of a PCAN Channel"</param>
/// <returns>"A TPCANStatus error code"</returns>
@ffi.Native<ffi.Uint32 Function(ffi.Uint16)>()
external int CAN_Reset(int Channel);

/// <summary>
/// Gets the current status of a PCAN Channel
/// </summary>
/// <param name="Channel">"The handle of a PCAN Channel"</param>
/// <returns>"A TPCANStatus error code"</returns>
@ffi.Native<ffi.Uint32 Function(ffi.Uint16)>()
external int CAN_GetStatus(int Channel);

/// <summary>
/// Reads a CAN message from the receive queue of a PCAN Channel
/// </summary>
/// <param name="Channel">"The handle of a PCAN Channel"</param>
/// <param name="MessageBuffer">"A TPCANMsg structure buffer to store the CAN message"</param>
/// <param name="TimestampBuffer">"A TPCANTimestamp structure buffer to get
/// the reception time of the message. If this value is not desired, this parameter
/// should be passed as NULL"</param>
/// <returns>"A TPCANStatus error code"</returns>
@ffi.Native<
  ffi.Uint32 Function(
    ffi.Uint16,
    ffi.Pointer<tagTPCANMsg>,
    ffi.Pointer<tagTPCANTimestamp>,
  )
>()
external int CAN_Read(
  int Channel,
  ffi.Pointer<tagTPCANMsg> MessageBuffer,
  ffi.Pointer<tagTPCANTimestamp> TimestampBuffer,
);

/// <summary>
/// Reads a CAN message from the receive queue of a FD capable PCAN Channel
/// </summary>
/// <param name="Channel">"The handle of a FD capable PCAN Channel"</param>
/// <param name="MessageBuffer">"A TPCANMsgFD structure buffer to store the CAN message"</param>
/// <param name="TimestampBuffer">"A TPCANTimestampFD buffer to get
/// the reception time of the message. If this value is not desired, this parameter
/// should be passed as NULL"</param>
/// <returns>"A TPCANStatus error code"</returns>
@ffi.Native<
  ffi.Uint32 Function(
    ffi.Uint16,
    ffi.Pointer<tagTPCANMsgFD>,
    ffi.Pointer<ffi.Uint64>,
  )
>()
external int CAN_ReadFD(
  int Channel,
  ffi.Pointer<tagTPCANMsgFD> MessageBuffer,
  ffi.Pointer<ffi.Uint64> TimestampBuffer,
);

/// <summary>
/// Transmits a CAN message
/// </summary>
/// <param name="Channel">"The handle of a PCAN Channel"</param>
/// <param name="MessageBuffer">"A TPCANMsg buffer with the message to be sent"</param>
/// <returns>"A TPCANStatus error code"</returns>
@ffi.Native<ffi.Uint32 Function(ffi.Uint16, ffi.Pointer<tagTPCANMsg>)>()
external int CAN_Write(int Channel, ffi.Pointer<tagTPCANMsg> MessageBuffer);

/// <summary>
/// Transmits a CAN message over a FD capable PCAN Channel
/// </summary>
/// <param name="Channel">"The handle of a FD capable PCAN Channel"</param>
/// <param name="MessageBuffer">"A TPCANMsgFD buffer with the message to be sent"</param>
/// <returns>"A TPCANStatus error code"</returns>
@ffi.Native<ffi.Uint32 Function(ffi.Uint16, ffi.Pointer<tagTPCANMsgFD>)>()
external int CAN_WriteFD(int Channel, ffi.Pointer<tagTPCANMsgFD> MessageBuffer);

/// <summary>
/// Configures the reception filter.
/// </summary>
/// <remarks>The message filter will be expanded with every call to
/// this function. If it is desired to reset the filter, please use
/// the CAN_SetValue function</remarks>
/// <param name="Channel">"The handle of a PCAN Channel"</param>
/// <param name="FromID">"The lowest CAN ID to be received"</param>
/// <param name="ToID">"The highest CAN ID to be received"</param>
/// <param name="Mode">"Message type, Standard (11-bit identifier) or
/// Extended (29-bit identifier)"</param>
/// <returns>"A TPCANStatus error code"</returns>
@ffi.Native<
  ffi.Uint32 Function(ffi.Uint16, ffi.Uint32, ffi.Uint32, ffi.Uint8)
>()
external int CAN_FilterMessages(int Channel, int FromID, int ToID, int Mode);

/// <summary>
/// Retrieves a PCAN Channel value
/// </summary>
/// <remarks>Parameters can be present or not according with the kind
/// of Hardware (PCAN Channel) being used. If a parameter is not available,
/// a PCAN_ERROR_ILLPARAMTYPE error will be returned</remarks>
/// <param name="Channel">"The handle of a PCAN Channel"</param>
/// <param name="Parameter">"The TPCANParameter parameter to get"</param>
/// <param name="Buffer">"Buffer for the parameter value"</param>
/// <param name="BufferLength">"Size in bytes of the buffer"</param>
/// <returns>"A TPCANStatus error code"</returns>
@ffi.Native<
  ffi.Uint32 Function(ffi.Uint16, ffi.Uint8, ffi.Pointer<ffi.Void>, ffi.Uint32)
>()
external int CAN_GetValue(
  int Channel,
  int Parameter,
  ffi.Pointer<ffi.Void> Buffer,
  int BufferLength,
);

/// <summary>
/// Configures or sets a PCAN Channel value
/// </summary>
/// <remarks>Parameters can be present or not according with the kind
/// of Hardware (PCAN Channel) being used. If a parameter is not available,
/// a PCAN_ERROR_ILLPARAMTYPE error will be returned</remarks>
/// <param name="Channel">"The handle of a PCAN Channel"</param>
/// <param name="Parameter">"The TPCANParameter parameter to set"</param>
/// <param name="Buffer">"Buffer with the value to be set"</param>
/// <param name="BufferLength">"Size in bytes of the buffer"</param>
/// <returns>"A TPCANStatus error code"</returns>
@ffi.Native<
  ffi.Uint32 Function(ffi.Uint16, ffi.Uint8, ffi.Pointer<ffi.Void>, ffi.Uint32)
>()
external int CAN_SetValue(
  int Channel,
  int Parameter,
  ffi.Pointer<ffi.Void> Buffer,
  int BufferLength,
);

/// <summary>
/// Returns a descriptive text of a given TPCANStatus error
/// code, in any desired language
/// </summary>
/// <remarks>The current languages available for translation are:
/// Neutral (0x00), German (0x07), English (0x09), Spanish (0x0A),
/// Italian (0x10) and French (0x0C)</remarks>
/// <param name="Error">"A TPCANStatus error code"</param>
/// <param name="Language">"Indicates a 'Primary language ID'"</param>
/// <param name="Buffer">"Buffer for a null terminated char array"</param>
/// <returns>"A TPCANStatus error code"</returns>
@ffi.Native<
  ffi.Uint32 Function(ffi.Uint32, ffi.Uint16, ffi.Pointer<ffi.Char>)
>()
external int CAN_GetErrorText(
  int Error,
  int Language,
  ffi.Pointer<ffi.Char> Buffer,
);

/// <summary>
/// Finds a PCAN-Basic channel that matches with the given parameters
/// </summary>
/// <param name="Parameters">A comma separated string contained pairs of
/// parameter-name/value to be matched within a PCAN-Basic channel</param>
/// <param name="FoundChannel">Buffer for returning the PCAN-Basic channel,
/// when found</param>
/// <returns>A TPCANStatus error code</returns>
@ffi.Native<
  ffi.Uint32 Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Uint16>)
>()
external int CAN_LookUpChannel(
  ffi.Pointer<ffi.Char> Parameters,
  ffi.Pointer<ffi.Uint16> FoundChannel,
);

/// /////////////////////////////////////////////////////////
final class tagTPCANMsg extends ffi.Struct {
  @ffi.Uint32()
  external int ID;

  @ffi.Uint8()
  external int MSGTYPE;

  @ffi.Uint8()
  external int LEN;

  @ffi.Array.multi([8])
  external ffi.Array<ffi.Uint8> DATA;
}

final class tagTPCANTimestamp extends ffi.Struct {
  @ffi.Uint32()
  external int millis;

  @ffi.Uint16()
  external int millis_overflow;

  @ffi.Uint16()
  external int micros;
}

final class tagTPCANMsgFD extends ffi.Struct {
  @ffi.Uint32()
  external int ID;

  @ffi.Uint8()
  external int MSGTYPE;

  @ffi.Uint8()
  external int DLC;

  @ffi.Array.multi([64])
  external ffi.Array<ffi.Uint8> DATA;
}

final class tagTPCANChannelInformation extends ffi.Struct {
  @ffi.Uint16()
  external int channel_handle;

  @ffi.Uint8()
  external int device_type;

  @ffi.Uint8()
  external int controller_number;

  @ffi.Uint32()
  external int device_features;

  @ffi.Array.multi([33])
  external ffi.Array<ffi.Char> device_name;

  @ffi.Uint32()
  external int device_id;

  @ffi.Uint32()
  external int channel_condition;
}

const int PCAN_NONEBUS = 0;

const int PCAN_ISABUS1 = 33;

const int PCAN_ISABUS2 = 34;

const int PCAN_ISABUS3 = 35;

const int PCAN_ISABUS4 = 36;

const int PCAN_ISABUS5 = 37;

const int PCAN_ISABUS6 = 38;

const int PCAN_ISABUS7 = 39;

const int PCAN_ISABUS8 = 40;

const int PCAN_DNGBUS1 = 49;

const int PCAN_PCIBUS1 = 65;

const int PCAN_PCIBUS2 = 66;

const int PCAN_PCIBUS3 = 67;

const int PCAN_PCIBUS4 = 68;

const int PCAN_PCIBUS5 = 69;

const int PCAN_PCIBUS6 = 70;

const int PCAN_PCIBUS7 = 71;

const int PCAN_PCIBUS8 = 72;

const int PCAN_PCIBUS9 = 1033;

const int PCAN_PCIBUS10 = 1034;

const int PCAN_PCIBUS11 = 1035;

const int PCAN_PCIBUS12 = 1036;

const int PCAN_PCIBUS13 = 1037;

const int PCAN_PCIBUS14 = 1038;

const int PCAN_PCIBUS15 = 1039;

const int PCAN_PCIBUS16 = 1040;

const int PCAN_USBBUS1 = 81;

const int PCAN_USBBUS2 = 82;

const int PCAN_USBBUS3 = 83;

const int PCAN_USBBUS4 = 84;

const int PCAN_USBBUS5 = 85;

const int PCAN_USBBUS6 = 86;

const int PCAN_USBBUS7 = 87;

const int PCAN_USBBUS8 = 88;

const int PCAN_USBBUS9 = 1289;

const int PCAN_USBBUS10 = 1290;

const int PCAN_USBBUS11 = 1291;

const int PCAN_USBBUS12 = 1292;

const int PCAN_USBBUS13 = 1293;

const int PCAN_USBBUS14 = 1294;

const int PCAN_USBBUS15 = 1295;

const int PCAN_USBBUS16 = 1296;

const int PCAN_PCCBUS1 = 97;

const int PCAN_PCCBUS2 = 98;

const int PCAN_LANBUS1 = 2049;

const int PCAN_LANBUS2 = 2050;

const int PCAN_LANBUS3 = 2051;

const int PCAN_LANBUS4 = 2052;

const int PCAN_LANBUS5 = 2053;

const int PCAN_LANBUS6 = 2054;

const int PCAN_LANBUS7 = 2055;

const int PCAN_LANBUS8 = 2056;

const int PCAN_LANBUS9 = 2057;

const int PCAN_LANBUS10 = 2058;

const int PCAN_LANBUS11 = 2059;

const int PCAN_LANBUS12 = 2060;

const int PCAN_LANBUS13 = 2061;

const int PCAN_LANBUS14 = 2062;

const int PCAN_LANBUS15 = 2063;

const int PCAN_LANBUS16 = 2064;

const int PCAN_ERROR_OK = 0;

const int PCAN_ERROR_XMTFULL = 1;

const int PCAN_ERROR_OVERRUN = 2;

const int PCAN_ERROR_BUSLIGHT = 4;

const int PCAN_ERROR_BUSHEAVY = 8;

const int PCAN_ERROR_BUSWARNING = 8;

const int PCAN_ERROR_BUSPASSIVE = 262144;

const int PCAN_ERROR_BUSOFF = 16;

const int PCAN_ERROR_ANYBUSERR = 262172;

const int PCAN_ERROR_QRCVEMPTY = 32;

const int PCAN_ERROR_QOVERRUN = 64;

const int PCAN_ERROR_QXMTFULL = 128;

const int PCAN_ERROR_REGTEST = 256;

const int PCAN_ERROR_NODRIVER = 512;

const int PCAN_ERROR_HWINUSE = 1024;

const int PCAN_ERROR_NETINUSE = 2048;

const int PCAN_ERROR_ILLHW = 5120;

const int PCAN_ERROR_ILLNET = 6144;

const int PCAN_ERROR_ILLCLIENT = 7168;

const int PCAN_ERROR_ILLHANDLE = 7168;

const int PCAN_ERROR_RESOURCE = 8192;

const int PCAN_ERROR_ILLPARAMTYPE = 16384;

const int PCAN_ERROR_ILLPARAMVAL = 32768;

const int PCAN_ERROR_UNKNOWN = 65536;

const int PCAN_ERROR_ILLDATA = 131072;

const int PCAN_ERROR_ILLMODE = 524288;

const int PCAN_ERROR_CAUTION = 33554432;

const int PCAN_ERROR_INITIALIZE = 67108864;

const int PCAN_ERROR_ILLOPERATION = 134217728;

const int PCAN_NONE = 0;

const int PCAN_PEAKCAN = 1;

const int PCAN_ISA = 2;

const int PCAN_DNG = 3;

const int PCAN_PCI = 4;

const int PCAN_USB = 5;

const int PCAN_PCC = 6;

const int PCAN_VIRTUAL = 7;

const int PCAN_LAN = 8;

const int PCAN_DEVICE_ID = 1;

const int PCAN_5VOLTS_POWER = 2;

const int PCAN_RECEIVE_EVENT = 3;

const int PCAN_MESSAGE_FILTER = 4;

const int PCAN_API_VERSION = 5;

const int PCAN_CHANNEL_VERSION = 6;

const int PCAN_BUSOFF_AUTORESET = 7;

const int PCAN_LISTEN_ONLY = 8;

const int PCAN_LOG_LOCATION = 9;

const int PCAN_LOG_STATUS = 10;

const int PCAN_LOG_CONFIGURE = 11;

const int PCAN_LOG_TEXT = 12;

const int PCAN_CHANNEL_CONDITION = 13;

const int PCAN_HARDWARE_NAME = 14;

const int PCAN_RECEIVE_STATUS = 15;

const int PCAN_CONTROLLER_NUMBER = 16;

const int PCAN_TRACE_LOCATION = 17;

const int PCAN_TRACE_STATUS = 18;

const int PCAN_TRACE_SIZE = 19;

const int PCAN_TRACE_CONFIGURE = 20;

const int PCAN_CHANNEL_IDENTIFYING = 21;

const int PCAN_CHANNEL_FEATURES = 22;

const int PCAN_BITRATE_ADAPTING = 23;

const int PCAN_BITRATE_INFO = 24;

const int PCAN_BITRATE_INFO_FD = 25;

const int PCAN_BUSSPEED_NOMINAL = 26;

const int PCAN_BUSSPEED_DATA = 27;

const int PCAN_IP_ADDRESS = 28;

const int PCAN_LAN_SERVICE_STATUS = 29;

const int PCAN_ALLOW_STATUS_FRAMES = 30;

const int PCAN_ALLOW_RTR_FRAMES = 31;

const int PCAN_ALLOW_ERROR_FRAMES = 32;

const int PCAN_INTERFRAME_DELAY = 33;

const int PCAN_ACCEPTANCE_FILTER_11BIT = 34;

const int PCAN_ACCEPTANCE_FILTER_29BIT = 35;

const int PCAN_IO_DIGITAL_CONFIGURATION = 36;

const int PCAN_IO_DIGITAL_VALUE = 37;

const int PCAN_IO_DIGITAL_SET = 38;

const int PCAN_IO_DIGITAL_CLEAR = 39;

const int PCAN_IO_ANALOG_VALUE = 40;

const int PCAN_FIRMWARE_VERSION = 41;

const int PCAN_ATTACHED_CHANNELS_COUNT = 42;

const int PCAN_ATTACHED_CHANNELS = 43;

const int PCAN_ALLOW_ECHO_FRAMES = 44;

const int PCAN_DEVICE_PART_NUMBER = 45;

const int PCAN_HARD_RESET_STATUS = 46;

const int PCAN_LAN_CHANNEL_DIRECTION = 47;

const int PCAN_DEVICE_GUID = 48;

const int PCAN_DEVICE_NUMBER = 1;

const int PCAN_PARAMETER_OFF = 0;

const int PCAN_PARAMETER_ON = 1;

const int PCAN_FILTER_CLOSE = 0;

const int PCAN_FILTER_OPEN = 1;

const int PCAN_FILTER_CUSTOM = 2;

const int PCAN_CHANNEL_UNAVAILABLE = 0;

const int PCAN_CHANNEL_AVAILABLE = 1;

const int PCAN_CHANNEL_OCCUPIED = 2;

const int PCAN_CHANNEL_PCANVIEW = 3;

const int LOG_FUNCTION_DEFAULT = 0;

const int LOG_FUNCTION_ENTRY = 1;

const int LOG_FUNCTION_PARAMETERS = 2;

const int LOG_FUNCTION_LEAVE = 4;

const int LOG_FUNCTION_WRITE = 8;

const int LOG_FUNCTION_READ = 16;

const int LOG_FUNCTION_ALL = 65535;

const int TRACE_FILE_SINGLE = 0;

const int TRACE_FILE_SEGMENTED = 1;

const int TRACE_FILE_DATE = 2;

const int TRACE_FILE_TIME = 4;

const int TRACE_FILE_OVERWRITE = 128;

const int TRACE_FILE_DATA_LENGTH = 256;

const int FEATURE_FD_CAPABLE = 1;

const int FEATURE_DELAY_CAPABLE = 2;

const int FEATURE_IO_CAPABLE = 4;

const int SERVICE_STATUS_STOPPED = 1;

const int SERVICE_STATUS_RUNNING = 4;

const int LAN_DIRECTION_READ = 1;

const int LAN_DIRECTION_WRITE = 2;

const int LAN_DIRECTION_READ_WRITE = 3;

const int MAX_LENGTH_HARDWARE_NAME = 33;

const int MAX_LENGTH_VERSION_STRING = 256;

const int PCAN_MESSAGE_STANDARD = 0;

const int PCAN_MESSAGE_RTR = 1;

const int PCAN_MESSAGE_EXTENDED = 2;

const int PCAN_MESSAGE_FD = 4;

const int PCAN_MESSAGE_BRS = 8;

const int PCAN_MESSAGE_ESI = 16;

const int PCAN_MESSAGE_ECHO = 32;

const int PCAN_MESSAGE_ERRFRAME = 64;

const int PCAN_MESSAGE_STATUS = 128;

const String LOOKUP_DEVICE_TYPE = 'devicetype';

const String LOOKUP_DEVICE_ID = 'deviceid';

const String LOOKUP_CONTROLLER_NUMBER = 'controllernumber';

const String LOOKUP_IP_ADDRESS = 'ipaddress';

const String LOOKUP_DEVICE_GUID = 'deviceguid';

const int PCAN_MODE_STANDARD = 0;

const int PCAN_MODE_EXTENDED = 2;

const int PCAN_BAUD_1M = 20;

const int PCAN_BAUD_800K = 22;

const int PCAN_BAUD_500K = 28;

const int PCAN_BAUD_250K = 284;

const int PCAN_BAUD_125K = 796;

const int PCAN_BAUD_100K = 17199;

const int PCAN_BAUD_95K = 49998;

const int PCAN_BAUD_83K = 34091;

const int PCAN_BAUD_50K = 18223;

const int PCAN_BAUD_47K = 5140;

const int PCAN_BAUD_33K = 35631;

const int PCAN_BAUD_20K = 21295;

const int PCAN_BAUD_10K = 26415;

const int PCAN_BAUD_5K = 32639;

const String PCAN_BR_CLOCK = 'f_clock';

const String PCAN_BR_CLOCK_MHZ = 'f_clock_mhz';

const String PCAN_BR_NOM_BRP = 'nom_brp';

const String PCAN_BR_NOM_TSEG1 = 'nom_tseg1';

const String PCAN_BR_NOM_TSEG2 = 'nom_tseg2';

const String PCAN_BR_NOM_SJW = 'nom_sjw';

const String PCAN_BR_NOM_SAMPLE = 'nom_sam';

const String PCAN_BR_DATA_BRP = 'data_brp';

const String PCAN_BR_DATA_TSEG1 = 'data_tseg1';

const String PCAN_BR_DATA_TSEG2 = 'data_tseg2';

const String PCAN_BR_DATA_SJW = 'data_sjw';

const String PCAN_BR_DATA_SAMPLE = 'data_ssp_offset';

const int PCAN_TYPE_ISA = 1;

const int PCAN_TYPE_ISA_SJA = 9;

const int PCAN_TYPE_ISA_PHYTEC = 4;

const int PCAN_TYPE_DNG = 2;

const int PCAN_TYPE_DNG_EPP = 3;

const int PCAN_TYPE_DNG_SJA = 5;

const int PCAN_TYPE_DNG_SJA_EPP = 6;
