# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from brainstem_sdk._proto import cms_pb2 as han__dog__message_dot_cms__pb2
from brainstem_sdk._proto import common_pb2 as han__dog__message_dot_common__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in han_dog_message/cms_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CmsStub(object):
    """四足机器人命令与监控服务。

    控制类 RPC（受仲裁器限制，遥控器优先级更高）：
    Enable / Disable / Walk / StandUp / SitDown

    仿真类 RPC（仅在 sim 模式下使用）：
    Tick / Step

    监控类 RPC（不受仲裁限制，任何客户端均可订阅）：
    ListenHistory / ListenImu / ListenJoint / GetStartTime / GetParams
    ──── 硬件控制 ────
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Enable = channel.unary_unary(
                '/han_dog.Cms/Enable',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.Disable = channel.unary_unary(
                '/han_dog.Cms/Disable',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.Walk = channel.unary_unary(
                '/han_dog.Cms/Walk',
                request_serializer=han__dog__message_dot_common__pb2.Vector3.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.StandUp = channel.unary_unary(
                '/han_dog.Cms/StandUp',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.SitDown = channel.unary_unary(
                '/han_dog.Cms/SitDown',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.Tick = channel.unary_unary(
                '/han_dog.Cms/Tick',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=han__dog__message_dot_cms__pb2.History.FromString,
                _registered_method=True)
        self.Step = channel.unary_unary(
                '/han_dog.Cms/Step',
                request_serializer=han__dog__message_dot_common__pb2.SimState.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.GetStartTime = channel.unary_unary(
                '/han_dog.Cms/GetStartTime',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_timestamp__pb2.Timestamp.FromString,
                _registered_method=True)
        self.GetCmsState = channel.unary_unary(
                '/han_dog.Cms/GetCmsState',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=han__dog__message_dot_cms__pb2.CmsState.FromString,
                _registered_method=True)
        self.ListenHistory = channel.unary_stream(
                '/han_dog.Cms/ListenHistory',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=han__dog__message_dot_cms__pb2.History.FromString,
                _registered_method=True)
        self.ListenCmsState = channel.unary_stream(
                '/han_dog.Cms/ListenCmsState',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=han__dog__message_dot_cms__pb2.CmsState.FromString,
                _registered_method=True)
        self.ListenImu = channel.unary_stream(
                '/han_dog.Cms/ListenImu',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=han__dog__message_dot_cms__pb2.Imu.FromString,
                _registered_method=True)
        self.ListenJoint = channel.unary_stream(
                '/han_dog.Cms/ListenJoint',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=han__dog__message_dot_cms__pb2.Joint.FromString,
                _registered_method=True)
        self.GetParams = channel.unary_unary(
                '/han_dog.Cms/GetParams',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=han__dog__message_dot_cms__pb2.Params.FromString,
                _registered_method=True)
        self.SwitchProfile = channel.unary_unary(
                '/han_dog.Cms/SwitchProfile',
                request_serializer=han__dog__message_dot_cms__pb2.ProfileRequest.SerializeToString,
                response_deserializer=han__dog__message_dot_cms__pb2.ProfileInfo.FromString,
                _registered_method=True)
        self.GetProfile = channel.unary_unary(
                '/han_dog.Cms/GetProfile',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=han__dog__message_dot_cms__pb2.ProfileInfo.FromString,
                _registered_method=True)
        self.GetVoltage = channel.unary_unary(
                '/han_dog.Cms/GetVoltage',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=han__dog__message_dot_cms__pb2.Voltage.FromString,
                _registered_method=True)
        self.GetMotorStatus = channel.unary_unary(
                '/han_dog.Cms/GetMotorStatus',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=han__dog__message_dot_cms__pb2.MotorStatusResponse.FromString,
                _registered_method=True)
        self.ClearMotorFault = channel.unary_unary(
                '/han_dog.Cms/ClearMotorFault',
                request_serializer=han__dog__message_dot_cms__pb2.ClearFaultRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.SetZero = channel.unary_unary(
                '/han_dog.Cms/SetZero',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class CmsServicer(object):
    """四足机器人命令与监控服务。

    控制类 RPC（受仲裁器限制，遥控器优先级更高）：
    Enable / Disable / Walk / StandUp / SitDown

    仿真类 RPC（仅在 sim 模式下使用）：
    Tick / Step

    监控类 RPC（不受仲裁限制，任何客户端均可订阅）：
    ListenHistory / ListenImu / ListenJoint / GetStartTime / GetParams
    ──── 硬件控制 ────
    """

    def Enable(self, request, context):
        """使能所有电机（硬件级操作，不经仲裁）。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Disable(self, request, context):
        """禁用所有电机（硬件级操作，不经仲裁）。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Walk(self, request, context):
        """──── 运动指令（经仲裁器，可能被拒绝） ────

        行走：传入方向向量 (x=前后, y=左右, z=旋转)，范围 [-1, 1]。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StandUp(self, request, context):
        """从坐姿过渡到站立姿态。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SitDown(self, request, context):
        """从站立过渡到坐姿。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Tick(self, request, context):
        """──── 仿真专用 ────

        推进一个仿真步（sim 模式），返回当前 History。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Step(self, request, context):
        """向控制器注入仿真传感器数据。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStartTime(self, request, context):
        """──── 查询与监控 ────

        获取服务启动时间（UTC）。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCmsState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListenHistory(self, request, context):
        """实时推理历史流：每个推理周期（~20ms）发送一帧。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListenCmsState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListenImu(self, request, context):
        """实时 IMU 数据流。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListenJoint(self, request, context):
        """实时关节数据流（单关节上报或全关节快照）。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetParams(self, request, context):
        """获取机器人模型参数。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SwitchProfile(self, request, context):
        """──── 策略切换 ────

        切换到指定策略。机器人必须在 Grounded 状态。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProfile(self, request, context):
        """获取当前策略信息。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVoltage(self, request, context):
        """──── 诊断 ────

        读取全部 16 个电机的总线电压 (V)。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMotorStatus(self, request, context):
        """查询全部 16 个电机的健康状态。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearMotorFault(self, request, context):
        """清除电机故障。joint_ids 为空则清除全部，否则只清指定关节。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetZero(self, request, context):
        """电机清零：把当前位置标记为零点并保存。必须在 Grounded 状态。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CmsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Enable': grpc.unary_unary_rpc_method_handler(
                    servicer.Enable,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'Disable': grpc.unary_unary_rpc_method_handler(
                    servicer.Disable,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'Walk': grpc.unary_unary_rpc_method_handler(
                    servicer.Walk,
                    request_deserializer=han__dog__message_dot_common__pb2.Vector3.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'StandUp': grpc.unary_unary_rpc_method_handler(
                    servicer.StandUp,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'SitDown': grpc.unary_unary_rpc_method_handler(
                    servicer.SitDown,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'Tick': grpc.unary_unary_rpc_method_handler(
                    servicer.Tick,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=han__dog__message_dot_cms__pb2.History.SerializeToString,
            ),
            'Step': grpc.unary_unary_rpc_method_handler(
                    servicer.Step,
                    request_deserializer=han__dog__message_dot_common__pb2.SimState.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetStartTime': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStartTime,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_timestamp__pb2.Timestamp.SerializeToString,
            ),
            'GetCmsState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCmsState,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=han__dog__message_dot_cms__pb2.CmsState.SerializeToString,
            ),
            'ListenHistory': grpc.unary_stream_rpc_method_handler(
                    servicer.ListenHistory,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=han__dog__message_dot_cms__pb2.History.SerializeToString,
            ),
            'ListenCmsState': grpc.unary_stream_rpc_method_handler(
                    servicer.ListenCmsState,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=han__dog__message_dot_cms__pb2.CmsState.SerializeToString,
            ),
            'ListenImu': grpc.unary_stream_rpc_method_handler(
                    servicer.ListenImu,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=han__dog__message_dot_cms__pb2.Imu.SerializeToString,
            ),
            'ListenJoint': grpc.unary_stream_rpc_method_handler(
                    servicer.ListenJoint,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=han__dog__message_dot_cms__pb2.Joint.SerializeToString,
            ),
            'GetParams': grpc.unary_unary_rpc_method_handler(
                    servicer.GetParams,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=han__dog__message_dot_cms__pb2.Params.SerializeToString,
            ),
            'SwitchProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.SwitchProfile,
                    request_deserializer=han__dog__message_dot_cms__pb2.ProfileRequest.FromString,
                    response_serializer=han__dog__message_dot_cms__pb2.ProfileInfo.SerializeToString,
            ),
            'GetProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProfile,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=han__dog__message_dot_cms__pb2.ProfileInfo.SerializeToString,
            ),
            'GetVoltage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVoltage,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=han__dog__message_dot_cms__pb2.Voltage.SerializeToString,
            ),
            'GetMotorStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMotorStatus,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=han__dog__message_dot_cms__pb2.MotorStatusResponse.SerializeToString,
            ),
            'ClearMotorFault': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearMotorFault,
                    request_deserializer=han__dog__message_dot_cms__pb2.ClearFaultRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'SetZero': grpc.unary_unary_rpc_method_handler(
                    servicer.SetZero,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'han_dog.Cms', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('han_dog.Cms', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Cms(object):
    """四足机器人命令与监控服务。

    控制类 RPC（受仲裁器限制，遥控器优先级更高）：
    Enable / Disable / Walk / StandUp / SitDown

    仿真类 RPC（仅在 sim 模式下使用）：
    Tick / Step

    监控类 RPC（不受仲裁限制，任何客户端均可订阅）：
    ListenHistory / ListenImu / ListenJoint / GetStartTime / GetParams
    ──── 硬件控制 ────
    """

    @staticmethod
    def Enable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/han_dog.Cms/Enable',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Disable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/han_dog.Cms/Disable',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Walk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/han_dog.Cms/Walk',
            han__dog__message_dot_common__pb2.Vector3.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StandUp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/han_dog.Cms/StandUp',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SitDown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/han_dog.Cms/SitDown',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Tick(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/han_dog.Cms/Tick',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            han__dog__message_dot_cms__pb2.History.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Step(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/han_dog.Cms/Step',
            han__dog__message_dot_common__pb2.SimState.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStartTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/han_dog.Cms/GetStartTime',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_timestamp__pb2.Timestamp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCmsState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/han_dog.Cms/GetCmsState',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            han__dog__message_dot_cms__pb2.CmsState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListenHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/han_dog.Cms/ListenHistory',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            han__dog__message_dot_cms__pb2.History.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListenCmsState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/han_dog.Cms/ListenCmsState',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            han__dog__message_dot_cms__pb2.CmsState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListenImu(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/han_dog.Cms/ListenImu',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            han__dog__message_dot_cms__pb2.Imu.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListenJoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/han_dog.Cms/ListenJoint',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            han__dog__message_dot_cms__pb2.Joint.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetParams(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/han_dog.Cms/GetParams',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            han__dog__message_dot_cms__pb2.Params.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SwitchProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/han_dog.Cms/SwitchProfile',
            han__dog__message_dot_cms__pb2.ProfileRequest.SerializeToString,
            han__dog__message_dot_cms__pb2.ProfileInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/han_dog.Cms/GetProfile',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            han__dog__message_dot_cms__pb2.ProfileInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetVoltage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/han_dog.Cms/GetVoltage',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            han__dog__message_dot_cms__pb2.Voltage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMotorStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/han_dog.Cms/GetMotorStatus',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            han__dog__message_dot_cms__pb2.MotorStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClearMotorFault(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/han_dog.Cms/ClearMotorFault',
            han__dog__message_dot_cms__pb2.ClearFaultRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetZero(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/han_dog.Cms/SetZero',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
