# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: brainstem_api/common.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'brainstem_api/common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x62rainstem_api/common.proto\x12\x10\x62rainstem.api.v1\x1a\x1egoogle/protobuf/duration.proto\"*\n\x07Vector3\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\"\x1c\n\nArrayFloat\x12\x0e\n\x06values\x18\x01 \x03(\x01\"\x19\n\x07Matrix4\x12\x0e\n\x06values\x18\x01 \x03(\x01\"\x1e\n\x0cMatrix4Int32\x12\x0e\n\x06values\x18\x01 \x03(\r\"8\n\nQuaternion\x12\t\n\x01w\x18\x01 \x01(\x01\x12\t\n\x01x\x18\x02 \x01(\x01\x12\t\n\x01y\x18\x03 \x01(\x01\x12\t\n\x01z\x18\x04 \x01(\x01\"_\n\x06\x41\x63tion\x12\'\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x19.brainstem.api.v1.Matrix4\x12,\n\ttimestamp\x18\x02 \x01(\x0b\x32\x19.google.protobuf.Duration\"\xad\x01\n\nRobotModel\x12)\n\x04type\x18\x01 \x01(\x0e\x32\x1b.brainstem.api.v1.RobotType\x12\x39\n\x16initial_joint_position\x18\x02 \x01(\x0b\x32\x19.brainstem.api.v1.Matrix4\x12\x39\n\x16initial_joint_velocity\x18\x03 \x01(\x0b\x32\x19.brainstem.api.v1.Matrix4\"\xfe\x01\n\x08SimState\x12,\n\tgyroscope\x18\x01 \x01(\x0b\x32\x19.brainstem.api.v1.Vector3\x12\x30\n\nquaternion\x18\x02 \x01(\x0b\x32\x1c.brainstem.api.v1.Quaternion\x12\x31\n\x0ejoint_position\x18\x03 \x01(\x0b\x32\x19.brainstem.api.v1.Matrix4\x12\x31\n\x0ejoint_velocity\x18\x04 \x01(\x0b\x32\x19.brainstem.api.v1.Matrix4\x12,\n\ttimestamp\x18\x05 \x01(\x0b\x32\x19.google.protobuf.Duration*5\n\tRobotType\x12\n\n\x06SKINNY\x10\x00\x12\x07\n\x03HAN\x10\x01\x12\x08\n\x04MINI\x10\x02\x12\t\n\x05MINI2\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'brainstem_api.common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ROBOTTYPE']._serialized_start=801
  _globals['_ROBOTTYPE']._serialized_end=854
  _globals['_VECTOR3']._serialized_start=80
  _globals['_VECTOR3']._serialized_end=122
  _globals['_ARRAYFLOAT']._serialized_start=124
  _globals['_ARRAYFLOAT']._serialized_end=152
  _globals['_MATRIX4']._serialized_start=154
  _globals['_MATRIX4']._serialized_end=179
  _globals['_MATRIX4INT32']._serialized_start=181
  _globals['_MATRIX4INT32']._serialized_end=211
  _globals['_QUATERNION']._serialized_start=213
  _globals['_QUATERNION']._serialized_end=269
  _globals['_ACTION']._serialized_start=271
  _globals['_ACTION']._serialized_end=366
  _globals['_ROBOTMODEL']._serialized_start=369
  _globals['_ROBOTMODEL']._serialized_end=542
  _globals['_SIMSTATE']._serialized_start=545
  _globals['_SIMSTATE']._serialized_end=799
# @@protoc_insertion_point(module_scope)
