# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: brainstem_api/mujoco.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'brainstem_api/mujoco.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from brainstem_api import common_pb2 as brainstem__api_dot_common__pb2
from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x62rainstem_api/mujoco.proto\x12\x10\x62rainstem.api.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1a\x62rainstem_api/common.proto\x1a\x1egoogle/protobuf/duration.proto\"\x93\x01\n\x0bViewerFrame\x12*\n\x04qpos\x18\x01 \x01(\x0b\x32\x1c.brainstem.api.v1.ArrayFloat\x12*\n\x04qvel\x18\x02 \x01(\x0b\x32\x1c.brainstem.api.v1.ArrayFloat\x12,\n\ttimestamp\x18\x03 \x01(\x0b\x32\x19.google.protobuf.Duration2\x89\x01\n\x06Mujoco\x12@\n\x08SetModel\x12\x1c.brainstem.api.v1.RobotModel\x1a\x16.google.protobuf.Empty\x12=\n\x04Step\x12\x19.brainstem.api.v1.Matrix4\x1a\x1a.brainstem.api.v1.SimState2M\n\x0cMujocoViewer\x12=\n\x04Play\x12\x1d.brainstem.api.v1.ViewerFrame\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'brainstem_api.mujoco_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VIEWERFRAME']._serialized_start=138
  _globals['_VIEWERFRAME']._serialized_end=285
  _globals['_MUJOCO']._serialized_start=288
  _globals['_MUJOCO']._serialized_end=425
  _globals['_MUJOCOVIEWER']._serialized_start=427
  _globals['_MUJOCOVIEWER']._serialized_end=504
# @@protoc_insertion_point(module_scope)
