# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from brainstem_api import common_pb2 as brainstem__api_dot_common__pb2
from brainstem_api import mujoco_pb2 as brainstem__api_dot_mujoco__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in brainstem_api/mujoco_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MujocoStub(object):
    """MuJoCo 物理仿真服务。
    由 Python 端实现，Dart 端作为客户端调用。
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetModel = channel.unary_unary(
                '/brainstem.api.v1.Mujoco/SetModel',
                request_serializer=brainstem__api_dot_common__pb2.RobotModel.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.Step = channel.unary_unary(
                '/brainstem.api.v1.Mujoco/Step',
                request_serializer=brainstem__api_dot_common__pb2.Matrix4.SerializeToString,
                response_deserializer=brainstem__api_dot_common__pb2.SimState.FromString,
                _registered_method=True)


class MujocoServicer(object):
    """MuJoCo 物理仿真服务。
    由 Python 端实现，Dart 端作为客户端调用。
    """

    def SetModel(self, request, context):
        """初始化仿真器：设置机器人模型和初始姿态。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Step(self, request, context):
        """执行一步物理仿真：传入目标关节角度，返回仿真后的传感器状态。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MujocoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetModel': grpc.unary_unary_rpc_method_handler(
                    servicer.SetModel,
                    request_deserializer=brainstem__api_dot_common__pb2.RobotModel.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'Step': grpc.unary_unary_rpc_method_handler(
                    servicer.Step,
                    request_deserializer=brainstem__api_dot_common__pb2.Matrix4.FromString,
                    response_serializer=brainstem__api_dot_common__pb2.SimState.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'brainstem.api.v1.Mujoco', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('brainstem.api.v1.Mujoco', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Mujoco(object):
    """MuJoCo 物理仿真服务。
    由 Python 端实现，Dart 端作为客户端调用。
    """

    @staticmethod
    def SetModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/brainstem.api.v1.Mujoco/SetModel',
            brainstem__api_dot_common__pb2.RobotModel.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Step(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/brainstem.api.v1.Mujoco/Step',
            brainstem__api_dot_common__pb2.Matrix4.SerializeToString,
            brainstem__api_dot_common__pb2.SimState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class MujocoViewerStub(object):
    """MuJoCo 可视化服务。
    用于将仿真/真机数据回放到 MuJoCo viewer 中。
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Play = channel.unary_unary(
                '/brainstem.api.v1.MujocoViewer/Play',
                request_serializer=brainstem__api_dot_mujoco__pb2.ViewerFrame.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class MujocoViewerServicer(object):
    """MuJoCo 可视化服务。
    用于将仿真/真机数据回放到 MuJoCo viewer 中。
    """

    def Play(self, request, context):
        """播放一帧：将广义坐标/速度发送到 viewer 进行渲染。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MujocoViewerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Play': grpc.unary_unary_rpc_method_handler(
                    servicer.Play,
                    request_deserializer=brainstem__api_dot_mujoco__pb2.ViewerFrame.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'brainstem.api.v1.MujocoViewer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('brainstem.api.v1.MujocoViewer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MujocoViewer(object):
    """MuJoCo 可视化服务。
    用于将仿真/真机数据回放到 MuJoCo viewer 中。
    """

    @staticmethod
    def Play(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/brainstem.api.v1.MujocoViewer/Play',
            brainstem__api_dot_mujoco__pb2.ViewerFrame.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
