# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: han_dog_message/mujoco.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'han_dog_message/mujoco.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from han_dog_message import common_pb2 as han__dog__message_dot_common__pb2
from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1chan_dog_message/mujoco.proto\x12\x07han_dog\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1chan_dog_message/common.proto\x1a\x1egoogle/protobuf/duration.proto\"\x81\x01\n\x0bViewerFrame\x12!\n\x04qpos\x18\x01 \x01(\x0b\x32\x13.han_dog.ArrayFloat\x12!\n\x04qvel\x18\x02 \x01(\x0b\x32\x13.han_dog.ArrayFloat\x12,\n\ttimestamp\x18\x03 \x01(\x0b\x32\x19.google.protobuf.Duration2n\n\x06Mujoco\x12\x37\n\x08SetModel\x12\x13.han_dog.RobotModel\x1a\x16.google.protobuf.Empty\x12+\n\x04Step\x12\x10.han_dog.Matrix4\x1a\x11.han_dog.SimState2D\n\x0cMujocoViewer\x12\x34\n\x04Play\x12\x14.han_dog.ViewerFrame\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'han_dog_message.mujoco_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VIEWERFRAME']._serialized_start=133
  _globals['_VIEWERFRAME']._serialized_end=262
  _globals['_MUJOCO']._serialized_start=264
  _globals['_MUJOCO']._serialized_end=374
  _globals['_MUJOCOVIEWER']._serialized_start=376
  _globals['_MUJOCOVIEWER']._serialized_end=444
# @@protoc_insertion_point(module_scope)
