// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

@ffi.Native<ffi.Void Function(ffi.Pointer<SerialPortInfoArray>)>()
external void CSerialPortAvailablePortInfosMalloc(
  ffi.Pointer<SerialPortInfoArray> portInfoArray,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<SerialPortInfoArray>)>()
external void CSerialPortAvailablePortInfosFree(
  ffi.Pointer<SerialPortInfoArray> portInfoArray,
);

@ffi.Native<i_handle_t Function()>()
external int CSerialPortMalloc();

@ffi.Native<ffi.Void Function(i_handle_t)>()
external void CSerialPortFree(int handle);

@ffi.Native<
  ffi.Void Function(
    i_handle_t,
    ffi.Pointer<ffi.Char>,
    ffi.Int,
    ffi.UnsignedInt,
    ffi.UnsignedInt,
    ffi.UnsignedInt,
    ffi.UnsignedInt,
    ffi.UnsignedInt,
  )
>(symbol: 'CSerialPortInit')
external void _CSerialPortInit(
  int handle,
  ffi.Pointer<ffi.Char> portName,
  int baudRate,
  int parity,
  int dataBits,
  int stopbits,
  int flowControl,
  int readBufferSize,
);

void CSerialPortInit(
  Darti_handle_t handle,
  ffi.Pointer<ffi.Char> portName,
  int baudRate,
  Parity parity,
  DataBits dataBits,
  StopBits stopbits,
  FlowControl flowControl,
  int readBufferSize,
) => _CSerialPortInit(
  handle,
  portName,
  baudRate,
  parity.value,
  dataBits.value,
  stopbits.value,
  flowControl.value,
  readBufferSize,
);

@ffi.Native<ffi.Void Function(i_handle_t, ffi.UnsignedInt)>(
  symbol: 'CSerialPortSetOperateMode',
)
external void _CSerialPortSetOperateMode(int handle, int operateMode);

void CSerialPortSetOperateMode(
  Darti_handle_t handle,
  OperateMode operateMode,
) => _CSerialPortSetOperateMode(handle, operateMode.value);

@ffi.Native<ffi.Int Function(i_handle_t)>()
external int CSerialPortOpen(int handle);

@ffi.Native<ffi.Void Function(i_handle_t)>()
external void CSerialPortClose(int handle);

@ffi.Native<ffi.Int Function(i_handle_t)>()
external int CSerialPortIsOpen(int handle);

@ffi.Native<ffi.Int Function(i_handle_t, pFunReadEvent)>()
external int CSerialPortConnectReadEvent(int handle, pFunReadEvent pFun);

@ffi.Native<ffi.Int Function(i_handle_t)>()
external int CSerialPortDisconnectReadEvent(int handle);

@ffi.Native<ffi.Int Function(i_handle_t, pFunHotPlugEvent)>()
external int CSerialPortConnectHotPlugEvent(int handle, pFunHotPlugEvent pFun);

@ffi.Native<ffi.Int Function(i_handle_t)>()
external int CSerialPortDisconnectHotPlugEvent(int handle);

@ffi.Native<
  ffi.Int Function(i_handle_t, pFunProtocolParser, pFunProtocolEvent)
>()
external int CSerialPortSetProtocolParser(
  int handle,
  pFunProtocolParser pParser,
  pFunProtocolEvent pFun,
);

@ffi.Native<ffi.UnsignedInt Function(i_handle_t)>()
external int CSerialPortGetReadBufferUsedLen(int handle);

@ffi.Native<ffi.Int Function(i_handle_t, ffi.Pointer<ffi.Void>, ffi.Int)>()
external int CSerialPortReadData(
  int handle,
  ffi.Pointer<ffi.Void> data,
  int size,
);

@ffi.Native<ffi.Int Function(i_handle_t, ffi.Pointer<ffi.Void>)>()
external int CSerialPortReadAllData(int handle, ffi.Pointer<ffi.Void> data);

@ffi.Native<ffi.Int Function(i_handle_t, ffi.Pointer<ffi.Void>, ffi.Int)>()
external int CSerialPortReadLineData(
  int handle,
  ffi.Pointer<ffi.Void> data,
  int size,
);

@ffi.Native<ffi.Int Function(i_handle_t, ffi.Pointer<ffi.Void>, ffi.Int)>()
external int CSerialPortWriteData(
  int handle,
  ffi.Pointer<ffi.Void> data,
  int size,
);

@ffi.Native<ffi.Void Function(i_handle_t, ffi.Int)>()
external void CSerialPortSetDebugModel(int handle, int isDebug);

@ffi.Native<ffi.Void Function(i_handle_t, ffi.UnsignedInt)>()
external void CSerialPortSetReadIntervalTimeout(int handle, int msecs);

@ffi.Native<ffi.UnsignedInt Function(i_handle_t)>()
external int CSerialPortGetReadIntervalTimeout(int handle);

@ffi.Native<ffi.Void Function(i_handle_t, ffi.UnsignedInt)>()
external void CSerialPortSetMinByteReadNotify(
  int handle,
  int minByteReadNotify,
);

@ffi.Native<ffi.Int Function(i_handle_t)>()
external int CSerialPortFlushBuffers(int handle);

@ffi.Native<ffi.Int Function(i_handle_t)>()
external int CSerialPortFlushReadBuffers(int handle);

@ffi.Native<ffi.Int Function(i_handle_t)>()
external int CSerialPortFlushWriteBuffers(int handle);

@ffi.Native<ffi.Int Function(i_handle_t)>()
external int CSerialPortGetLastError(int handle);

@ffi.Native<ffi.Pointer<ffi.Char> Function(i_handle_t)>()
external ffi.Pointer<ffi.Char> CSerialPortGetLastErrorMsg(int handle);

@ffi.Native<ffi.Void Function(i_handle_t)>()
external void CSerialPortClearError(int handle);

@ffi.Native<ffi.Void Function(i_handle_t, ffi.Pointer<ffi.Char>)>()
external void CSerialPortSetPortName(
  int handle,
  ffi.Pointer<ffi.Char> portName,
);

@ffi.Native<ffi.Pointer<ffi.Char> Function(i_handle_t)>()
external ffi.Pointer<ffi.Char> CSerialPortGetPortName(int handle);

@ffi.Native<ffi.Void Function(i_handle_t, ffi.Int)>()
external void CSerialPortSetBaudRate(int handle, int baudRate);

@ffi.Native<ffi.Int Function(i_handle_t)>()
external int CSerialPortGetBaudRate(int handle);

@ffi.Native<ffi.Void Function(i_handle_t, ffi.UnsignedInt)>(
  symbol: 'CSerialPortSetParity',
)
external void _CSerialPortSetParity(int handle, int parity);

void CSerialPortSetParity(Darti_handle_t handle, Parity parity) =>
    _CSerialPortSetParity(handle, parity.value);

@ffi.Native<ffi.UnsignedInt Function(i_handle_t)>(
  symbol: 'CSerialPortGetParity',
)
external int _CSerialPortGetParity(int handle);

Parity CSerialPortGetParity(Darti_handle_t handle) =>
    Parity.fromValue(_CSerialPortGetParity(handle));

@ffi.Native<ffi.Void Function(i_handle_t, ffi.UnsignedInt)>(
  symbol: 'CSerialPortSetDataBits',
)
external void _CSerialPortSetDataBits(int handle, int dataBits);

void CSerialPortSetDataBits(Darti_handle_t handle, DataBits dataBits) =>
    _CSerialPortSetDataBits(handle, dataBits.value);

@ffi.Native<ffi.UnsignedInt Function(i_handle_t)>(
  symbol: 'CSerialPortGetDataBits',
)
external int _CSerialPortGetDataBits(int handle);

DataBits CSerialPortGetDataBits(Darti_handle_t handle) =>
    DataBits.fromValue(_CSerialPortGetDataBits(handle));

@ffi.Native<ffi.Void Function(i_handle_t, ffi.UnsignedInt)>(
  symbol: 'CSerialPortSetStopBits',
)
external void _CSerialPortSetStopBits(int handle, int stopbits);

void CSerialPortSetStopBits(Darti_handle_t handle, StopBits stopbits) =>
    _CSerialPortSetStopBits(handle, stopbits.value);

@ffi.Native<ffi.UnsignedInt Function(i_handle_t)>(
  symbol: 'CSerialPortGetStopBits',
)
external int _CSerialPortGetStopBits(int handle);

StopBits CSerialPortGetStopBits(Darti_handle_t handle) =>
    StopBits.fromValue(_CSerialPortGetStopBits(handle));

@ffi.Native<ffi.Void Function(i_handle_t, ffi.UnsignedInt)>(
  symbol: 'CSerialPortSetFlowControl',
)
external void _CSerialPortSetFlowControl(int handle, int flowControl);

void CSerialPortSetFlowControl(
  Darti_handle_t handle,
  FlowControl flowControl,
) => _CSerialPortSetFlowControl(handle, flowControl.value);

@ffi.Native<ffi.UnsignedInt Function(i_handle_t)>(
  symbol: 'CSerialPortGetFlowControl',
)
external int _CSerialPortGetFlowControl(int handle);

FlowControl CSerialPortGetFlowControl(Darti_handle_t handle) =>
    FlowControl.fromValue(_CSerialPortGetFlowControl(handle));

@ffi.Native<ffi.Void Function(i_handle_t, ffi.UnsignedInt)>()
external void CSerialPortSetReadBufferSize(int handle, int size);

@ffi.Native<ffi.UnsignedInt Function(i_handle_t)>()
external int CSerialPortGetReadBufferSize(int handle);

@ffi.Native<ffi.Void Function(i_handle_t, ffi.Int)>()
external void CSerialPortSetDtr(int handle, int set);

@ffi.Native<ffi.Void Function(i_handle_t, ffi.Int)>()
external void CSerialPortSetRts(int handle, int set);

@ffi.Native<ffi.Pointer<ffi.Char> Function(i_handle_t)>()
external ffi.Pointer<ffi.Char> CSerialPortGetVersion(int handle);

typedef i_handle_t = ffi.UnsignedLongLong;
typedef Darti_handle_t = int;

final class SerialPortInfo extends ffi.Struct {
  @ffi.Array.multi([256])
  external ffi.Array<ffi.Char> portName;

  @ffi.Array.multi([256])
  external ffi.Array<ffi.Char> description;

  @ffi.Array.multi([256])
  external ffi.Array<ffi.Char> hardwareId;
}

final class SerialPortInfoArray extends ffi.Struct {
  external ffi.Pointer<SerialPortInfo> portInfo;

  @ffi.UnsignedInt()
  external int size;
}

final class ProtocolResult extends ffi.Struct {
  @ffi.Array.multi([256])
  external ffi.Array<ffi.UnsignedChar> data;

  @ffi.UnsignedInt()
  external int len;
}

final class ProtocolResultArray extends ffi.Struct {
  external ffi.Pointer<ProtocolResult> result;

  @ffi.UnsignedInt()
  external int size;
}

enum OperateMode {
  AsynchronousOperate(0),
  SynchronousOperate(1);

  final int value;
  const OperateMode(this.value);

  static OperateMode fromValue(int value) => switch (value) {
    0 => AsynchronousOperate,
    1 => SynchronousOperate,
    _ => throw ArgumentError('Unknown value for OperateMode: $value'),
  };
}

enum DataBits {
  DataBits5(5),
  DataBits6(6),
  DataBits7(7),
  DataBits8(8);

  final int value;
  const DataBits(this.value);

  static DataBits fromValue(int value) => switch (value) {
    5 => DataBits5,
    6 => DataBits6,
    7 => DataBits7,
    8 => DataBits8,
    _ => throw ArgumentError('Unknown value for DataBits: $value'),
  };
}

enum Parity {
  ParityNone(0),
  ParityOdd(1),
  ParityEven(2),
  ParityMark(3),
  ParitySpace(4);

  final int value;
  const Parity(this.value);

  static Parity fromValue(int value) => switch (value) {
    0 => ParityNone,
    1 => ParityOdd,
    2 => ParityEven,
    3 => ParityMark,
    4 => ParitySpace,
    _ => throw ArgumentError('Unknown value for Parity: $value'),
  };
}

enum StopBits {
  StopOne(0),
  StopOneAndHalf(1),
  StopTwo(2);

  final int value;
  const StopBits(this.value);

  static StopBits fromValue(int value) => switch (value) {
    0 => StopOne,
    1 => StopOneAndHalf,
    2 => StopTwo,
    _ => throw ArgumentError('Unknown value for StopBits: $value'),
  };
}

enum FlowControl {
  FlowNone(0),
  FlowHardware(1),
  FlowSoftware(2);

  final int value;
  const FlowControl(this.value);

  static FlowControl fromValue(int value) => switch (value) {
    0 => FlowNone,
    1 => FlowHardware,
    2 => FlowSoftware,
    _ => throw ArgumentError('Unknown value for FlowControl: $value'),
  };
}

typedef pFunReadEventFunction =
    ffi.Void Function(i_handle_t, ffi.Pointer<ffi.Char>, ffi.UnsignedInt);
typedef DartpFunReadEventFunction =
    void Function(Darti_handle_t, ffi.Pointer<ffi.Char>, int);
typedef pFunReadEvent = ffi.Pointer<ffi.NativeFunction<pFunReadEventFunction>>;
typedef pFunHotPlugEventFunction =
    ffi.Void Function(i_handle_t, ffi.Pointer<ffi.Char>, ffi.Int);
typedef DartpFunHotPlugEventFunction =
    void Function(Darti_handle_t, ffi.Pointer<ffi.Char>, int);
typedef pFunHotPlugEvent =
    ffi.Pointer<ffi.NativeFunction<pFunHotPlugEventFunction>>;
typedef pFunProtocolParserFunction =
    ffi.UnsignedInt Function(
      i_handle_t,
      ffi.Pointer<ffi.Void>,
      ffi.UnsignedInt,
      ffi.Pointer<ProtocolResultArray>,
    );
typedef DartpFunProtocolParserFunction =
    int Function(
      Darti_handle_t,
      ffi.Pointer<ffi.Void>,
      int,
      ffi.Pointer<ProtocolResultArray>,
    );
typedef pFunProtocolParser =
    ffi.Pointer<ffi.NativeFunction<pFunProtocolParserFunction>>;
typedef pFunProtocolEventFunction =
    ffi.Void Function(i_handle_t, ffi.Pointer<ProtocolResult>);
typedef DartpFunProtocolEventFunction =
    void Function(Darti_handle_t, ffi.Pointer<ProtocolResult>);
typedef pFunProtocolEvent =
    ffi.Pointer<ffi.NativeFunction<pFunProtocolEventFunction>>;
